name: "Push linuxptp daemon on merge to main"

permissions:
  contents: read
  packages: write  # This gives GitHub Actions permission to push to GHCR
  
env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  BUILD_PLATFORMS: linux/amd64

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image-linuxptp-daemon:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username:  ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
               
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push linuxptp-daemon
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true 
          platforms: ${{ env.BUILD_PLATFORMS }}
          sbom: false 
          provenance: false 
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: ./Dockerfile
