name: golangci-lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    if: false  # This prevents the job from running
    name: Run GolangCI-Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23  # Change this to match your Go version

      - name: lint test
        run: make lint
          
