name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  triage:
    if: false  # This prevents the job from running
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
