name: Unit Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x]  # Use valid versions
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Dependencies
        run: go mod tidy && go mod download

      - name: Run Tests
        run: make test
