on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Revive Action by pulling pre-built image
      uses: docker://morphy/revive-action:v2
      with:
        exclude: "./vendor/..."

    - name: Run go fmt
      run: go fmt ./...
      #run: diff -u <(echo -n) <(gofmt -d -s .)
      
    - name: Run go vet
      run: go vet ./...
    - name: Run Test
      run: make test

